// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldSalt holds the string denoting the salt field in the database.
	FieldSalt = "salt"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldIntro holds the string denoting the intro field in the database.
	FieldIntro = "intro"
	// FieldCoin holds the string denoting the coin field in the database.
	FieldCoin = "coin"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePosts holds the string denoting the posts edge name in mutations.
	EdgePosts = "posts"
	// EdgeFavoritePosts holds the string denoting the favorite_posts edge name in mutations.
	EdgeFavoritePosts = "favorite_posts"
	// EdgeCoins holds the string denoting the coins edge name in mutations.
	EdgeCoins = "coins"
	// Table holds the table name of the user in the database.
	Table = "users"
	// PostsTable is the table that holds the posts relation/edge.
	PostsTable = "posts"
	// PostsInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostsInverseTable = "posts"
	// PostsColumn is the table column denoting the posts relation/edge.
	PostsColumn = "user_posts"
	// FavoritePostsTable is the table that holds the favorite_posts relation/edge. The primary key declared below.
	FavoritePostsTable = "user_favorite_posts"
	// FavoritePostsInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	FavoritePostsInverseTable = "posts"
	// CoinsTable is the table that holds the coins relation/edge.
	CoinsTable = "coins"
	// CoinsInverseTable is the table name for the Coin entity.
	// It exists in this package in order to avoid circular dependency with the "coin" package.
	CoinsInverseTable = "coins"
	// CoinsColumn is the table column denoting the coins relation/edge.
	CoinsColumn = "user_coins"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAccount,
	FieldPassword,
	FieldSalt,
	FieldAvatarURL,
	FieldIntro,
	FieldCoin,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// FavoritePostsPrimaryKey and FavoritePostsColumn2 are the table columns denoting the
	// primary key for the favorite_posts relation (M2M).
	FavoritePostsPrimaryKey = []string{"user_id", "post_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCoin holds the default value on creation for the "coin" field.
	DefaultCoin int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
