// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Coin is the predicate function for coin builders.
type Coin func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
